### ISSUE TITLE
Yelp Statistics Question

### ISSUE THREAD

**Issue by RuihongQiu** [RUCAIBox/RecSysDatasets#95]
Hi,

Thank you for providing so many processed datasets.

I have a question when using the ```yelp``` dataset with RecBole.

I mainly use it for the sequential recommendation.

The general statistics of ```yelp``` is like:
From [S3Rec paper](https://dl.acm.org/doi/pdf/10.1145/3340531.3411954)
![image](https://user-images.githubusercontent.com/17882988/127488937-b062a3b8-ff35-463e-a090-7e40bb8bcae4.png)
From [BERT4Rec paper](https://arxiv.org/pdf/1904.06690.pdf)
![image](https://user-images.githubusercontent.com/17882988/127489026-f70f93e5-9f09-4979-8aea-2919e2ce615b.png)

They say they both filter out the items and users appearing less than 5 times.
I firstly download the processed dataset from [google drive](https://drive.google.com/drive/folders/1xUdtXEtbkNOMw8eGpLHHp3R8iIwcdJT9). When I set the dataset config in RecBole as:
```yaml
max_user_inter_num = None
min_user_inter_num = 5
max_item_inter_num = None
min_item_inter_num = 5
```

The logging statistics of ```yelp``` is as:
```yaml
29 Jul 20:04    INFO  yelp
The number of users: 329840
Average actions of users: 15.778049290714561
The number of items: 124462
Average actions of items: 41.81403009778163
The number of inters: 5204216
The sparsity of the dataset: 99.98732303718786%
```

Why is it so large and so different from the other papers? Is that my config is wrong somewhere?

**Comment by RuihongQiu** [comment]
I found out that in the preprocessing of [S3Rec](https://github.com/RUCAIBox/CIKM2020-S3Rec/blob/2a81540ae18615d88ef88227b0c066e5b74781e5/data/data_process.py#L319), there is a time filtering. Only interactions in 2019 will be considered. Are there any similar args can be used in RecBole?

**Comment by hyp1231** [comment]
Hi,
In RecBole 0.2.1, you can use `lowest_val` and `highest_val` to filter interactions.
Details can be found in our [API Doc](https://recbole.io/docs/user_guide/data/data_args.html#filter-by-value).

**Comment by RuihongQiu** [comment]
Thank you for the great suggestion.

Using the following config:
```yaml
min_user_inter_num: 5
min_item_inter_num: 5
lowest_val:
    timestamp: 1546264800
highest_val:
    timestamp: 1577714400
```

Already have a similar result:

```yaml
31 Jul 10:08    INFO  yelp
The number of users: 30500
Average actions of users: 10.399750811502017
The number of items: 20069
Average actions of items: 15.805361769982062
The number of inters: 317182
The sparsity of the dataset: 99.94818172387231%
```
